### ISSUE TITLE
Working with Latest React-Native?

### ISSUE THREAD

**Issue by indivisable** [greghe/react-native-particle-system#6]
Trying to get this working with Latest React, I got it compiling but nothing renders... any tips?

I mainly changed:

Separated React from React-Native

```
var React = require('react');
var ReactNative = require('react-native');

var {
  View
} = ReactNative;
```

And changed the export:

```
var GPHParticleView = ReactNative.requireNativeComponent('GPHParticleView', null);
module.exports = ReactNative.requireNativeComponent('GPHParticleCell', null);
```

Also changed the image source:

`<Image source={require("../../../assets/particles/spark.png")} style={{top:0, left:0, width:64, height:64}}/>`

**Comment by MattFoley** [comment]
This should be fixed now, there was some native code that needed to be updated.

**Comment by indivisable** [comment]
That is great @MattFoley I'll give it a try later tonight, thanks for this!

**Comment by indivisable** [comment]
@MattFoley Could you let me know which version of RN you tested with? I am trying with 0.36 without success. No errors just does not render, I'll see if I can debug to give you more details.

![image](https://cloud.githubusercontent.com/assets/22860891/21841142/8e0d2556-d7a6-11e6-8708-36133224f548.png)

**Comment by indivisable** [comment]
Confirmed it is working with RN 0.36, seems to be an issue with how I am integrating into my project.
 
Update: After fully removing and relinking the project in XCode it worked!

**Comment by MattFoley** [comment]
I've updated this again to work with RN 0.40+, there's a branch for it.
