### ISSUE TITLE
Confetti Mode

### ISSUE THREAD

**Issue by indivisable** [greghe/react-native-particle-system#8]
Would library be good for making Confetti? For example:

https://github.com/sudeepag/SAConfettiView

**Comment by MattFoley** [comment]
Yup, this would definitely be able to do that. Check out Particle Playground, that can help you make the confetti, and then you can use the values with this library.

**Comment by indivisable** [comment]
https://www.assetstore.unity3d.com/en/#!/content/13325 you mean this Unity Plugin?

**Comment by MattFoley** [comment]
Nah, this guy: https://itunes.apple.com/us/app/particle-playground/id600661093?mt=12

I use that when I'm working with CAParticleLayer

**Comment by indivisable** [comment]
Wow this is perfect, thanks for the tip! Should put in the docs that this is compatible, being able to prototype with this tool and use the params in the library make it even better.
